import { precacheAndRoute } from "workbox-precaching";

// Precache the assets generated by VitePWA (listed in __WB_MANIFEST)
precacheAndRoute(self.__WB_MANIFEST);

// Listen for the 'SKIP_WAITING' message and activate the service worker immediately
self.addEventListener("message", (event) => {
    if (event.data && event.data.type === "SKIP_WAITING") {
        self.skipWaiting();
    }
});

// Activate the service worker and claim control of all clients
self.addEventListener("activate", (event) => {
    event.waitUntil(self.clients.claim());
});